'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {Domino,Lotto,deck,total}=require('../dist/engine.js');
function seeded(seed){return ()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};}
function bare(mode='classic',count=2){const g=new Domino(mode,count,seeded(1));g.hands=Array.from({length:count},()=>[]);g.stock=[];g.chain=[];g.turn=0;g.scores=Array(count).fill(0);return g;}
function t(a,b){return {id:`${Math.min(a,b)}-${Math.max(a,b)}`,a,b};}
test('double-six deck has 28 unique tiles and deals every tile exactly once',()=>{assert.equal(deck().length,28);for(const count of [2,3,4]){const g=new Domino('classic',count,seeded(count));const ids=[...g.hands.flat(),...g.stock].map(t=>t.id);assert.equal(ids.length,28);assert.equal(new Set(ids).size,28);assert.ok(g.hands.every(h=>h.length===7));}});
test('highest double holder starts',()=>{for(let seed=1;seed<30;seed++){const g=new Domino('classic',4,seeded(seed));let best=-1,player=-1;g.hands.forEach((hand,p)=>hand.forEach(tile=>{const rank=tile.a===tile.b?100+tile.a:tile.a+tile.b;if(rank>best){best=rank;player=p;}}));assert.equal(g.turn,player);}});
test('only matching ends are accepted; wrong moves leave state unchanged',()=>{const g=bare();g.chain=[t(2,4)];g.hands=[[t(1,2),t(4,6),t(3,5)],[t(0,0)]];assert.deepEqual(g.legal().map(m=>m.sides),[['left'],['right']]);assert.throws(()=>g.play(2,'right'));assert.equal(g.hands[0].length,3);g.play(0,'left');assert.equal(g.chain[0].b,g.chain[1].a);assert.equal(g.chain[0].a,1);});
test('drawing and passing cannot bypass a legal move',()=>{const g=bare();g.chain=[t(1,2)];g.hands=[[t(2,3)],[t(4,5)]];g.stock=[t(0,0)];assert.throws(()=>g.draw());assert.throws(()=>g.pass());assert.equal(g.stock.length,1);});
test('drawing retains the turn and stock exhaustion permits a pass',()=>{const g=bare();g.chain=[t(1,2)];g.hands=[[t(3,4)],[t(5,6)]];g.stock=[t(0,0)];g.draw();assert.equal(g.turn,0);assert.equal(g.hands[0].length,2);g.pass();assert.equal(g.turn,1);});
test('blocked game chooses minimum pips and preserves ties',()=>{const g=bare();g.chain=[t(1,2)];g.hands=[[t(3,3)],[t(0,6)]];g.pass();g.pass();assert.equal(g.finished,true);assert.deepEqual(g.winners,[0,1]);});
test('empty hand finishes classic game immediately',()=>{const g=bare();g.chain=[t(1,2)];g.hands=[[t(2,3)],[t(4,4)]];g.play(0);assert.equal(g.finished,true);assert.deepEqual(g.winners,[0]);assert.throws(()=>g.play(0));});
test('all-fives counts end doubles and awards divisible sums',()=>{const g=bare('telephone');g.chain=[t(2,2),t(2,6)];assert.equal(g.openSum(),10);g.hands=[[t(1,6),t(0,0)],[t(3,4)]];const result=g.play(0);assert.equal(g.openSum(),5);assert.equal(result.points,5);assert.equal(g.scores[0],5);const first=bare('telephone');first.chain=[t(5,5)];assert.equal(first.openSum(),10);});
test('telephone awards rounded remaining pips before choosing highest score',()=>{const g=bare('telephone');g.chain=[t(1,2)];g.hands=[[t(2,3)],[t(4,4)]];g.scores=[0,30];g.play(0);assert.equal(g.scores[0],10);assert.deepEqual(g.winners,[1]);});
test('simulated domino games terminate and keep every tile intact',()=>{for(const mode of ['classic','telephone'])for(const count of [2,3,4])for(let seed=1;seed<=80;seed++){const g=new Domino(mode,count,seeded(seed));let turns=0;while(!g.finished&&turns++<400){g.botMove();const tiles=[...g.chain,...g.hands.flat(),...g.stock];assert.equal(tiles.length,28);assert.equal(new Set(tiles.map(t=>t.id)).size,28);for(let i=1;i<g.chain.length;i++)assert.equal(g.chain[i-1].b,g.chain[i].a);}assert.ok(g.finished,`${mode}/${count}/${seed} must end`);assert.ok(g.winners.length);assert.ok(g.scores.every(Number.isFinite));}});
test('lotto tickets have 15 unique numbers, five per row and correct columns',()=>{for(let seed=1;seed<=200;seed++){const g=new Lotto(4,seeded(seed));for(const board of g.tickets){assert.ok(board.every(row=>row.filter(n=>n!==null).length===5));const numbers=board.flat().filter(n=>n!==null);assert.equal(numbers.length,15);assert.equal(new Set(numbers).size,15);for(let c=0;c<9;c++){const col=board.map(row=>row[c]).filter(n=>n!==null);assert.ok(col.length>=1&&col.length<=3);assert.deepEqual(col,col.slice().sort((a,b)=>a-b));assert.ok(col.every(n=>n>=(c===0?1:c*10)&&n<=(c===8?90:c*10+9)));}}}});
test('lotto draws without replacement and winners have fully called tickets',()=>{for(let seed=1;seed<=150;seed++){const g=new Lotto(4,seeded(seed));while(!g.finished)g.draw();assert.equal(new Set(g.called).size,g.called.length);assert.ok(g.called.length<=90);assert.ok(g.winners.length);g.winners.forEach(i=>assert.equal(g.matched(i),15));assert.throws(()=>g.draw());}});
test('simultaneous lotto completions share the win',()=>{const g=new Lotto(2,seeded(10));g.tickets[1]=g.tickets[0].map(row=>row.slice());const nums=g.tickets[0].flat().filter(n=>n!==null);g.bag=nums.slice().reverse();while(!g.finished)g.draw();assert.deepEqual(g.winners,[0,1]);});
